export const BACK_UP_FAKTURA_REQUEST = 'BACK_UP_FAKTURA_REQUEST';
export const BACK_UP_FAKTURA_SUCCESS = 'BACK_UP_FAKTURA_SUCCESS';
export const BACK_UP_FAKTURA_FAIL = 'BACK_UP_FAKTURA_FAIL';

export const GET_BACK_UP_FAKTURE_REQUEST = 'GET_BACK_UP_FAKTURE_REQUEST';
export const GET_BACK_UP_FAKTURE_SUCCESS = 'GET_BACK_UP_FAKTURE_SUCCESS';
export const GET_BACK_UP_FAKTURE_FAIL = 'GET_BACK_UP_FAKTURE_FAIL';