export const GET_ALL_CLIENTS_REQUEST = 'GET_ALL_CLIENTS_REQUEST';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_RESET = 'GET_ALL_CLIENTS_RESET';
export const GET_ALL_CLIENTS_FAIL = 'GET_ALL_CLIENTS_FAIL';
export const ALL_CLIENTS_UPDATE = 'ALL_CLIENTS_UPDATE'

export const GET_SINGLE_CLIENT_REQUEST = 'GET_SINGLE_CLIENT_REQUEST';
export const GET_SINGLE_CLIENT_RESET = 'GET_SINGLE_CLIENT_RESET'
export const GET_SINGLE_CLIENT_SUCCESS = 'GET_SINGLE_CLIENT_SUCCESS';
export const GET_SINGLE_CLIENT_FAIL = 'GET_SINGLE_CLIENT_FAIL';

export const CLIENT_SAVE_REQUEST = 'CLIENT_SAVE_REQUEST';
export const CLIENT_SAVE_SUCCESS = 'CLIENT_SAVE_SUCCESS';
export const CLIENT_SAVE_FAIL = 'CLIENT_SAVE_FAIL';

export const CLIENT_UPDATE_REQUEST = 'CLIENT_UPDATE_REQUEST';
export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS';
export const CLIENT_UPDATE_FAIL = 'CLIENT_UPDATE_FAIL';

export const CLIENT_DELETE_REQUEST = 'CLIENT_DELETE_REQUEST';
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS';
export const CLIENT_DELETE_FAIL = 'CLIENT_DELETE_FAIL';