export const GET_ALL_CONTRACTS_REQUEST = 'GET_ALL_CONTRACTS_REQUEST';
export const GET_ALL_CONTRACTS_SUCCESS = 'GET_ALL_CONTRACTS_SUCCESS';
export const GET_ALL_CONTRACTS_RESET = 'GET_ALL_CONTRACTS_RESET';
export const GET_ALL_CONTRACTS_FAIL = 'GET_ALL_CONTRACTS_FAIL';
export const ALL_CONTRACTS_UPDATE = 'ALL_CONTRACTS_UPDATE';

export const GET_SINGLE_CONTRACT_REQUEST = 'GET_SINGLE_CONTRACT_REQUEST';
export const GET_SINGLE_CONTRACT_SUCCESS = 'GET_SINGLE_CONTRACT_SUCCESS';
export const GET_SINGLE_CONTRACT_RESET = 'GET_SINGLE_CONTRACT_RESET';
export const GET_SINGLE_CONTRACT_FAIL = 'GET_SINGLE_CONTRACT_FAIL';

export const GET_SINGLE_CONTRACT_BY_CLIENT_ID_REQUEST = 'GET_SINGLE_CONTRACT_BY_CLIENT_ID_REQUEST';
export const GET_SINGLE_CONTRACT_BY_CLIENT_ID_SUCCESS = 'GET_SINGLE_CONTRACT_BY_CLIENT_ID_SUCCESS';
export const GET_SINGLE_CONTRACT_BY_CLIENT_ID_FAIL = 'GET_SINGLE_CONTRACT_BY_CLIENT_ID_FAIL';


export const CONTRACT_SAVE_REQUEST = 'CONTRACT_SAVE_REQUEST';
export const CONTRACT_SAVE_SUCCESS = 'CONTRACT_SAVE_SUCCESS';
export const CONTRACT_SAVE_FAIL = 'CONTRACT_SAVE_FAIL';

export const CONTRACT_DELETE_REQUEST = 'CONTRACT_DELETE_REQUEST';
export const CONTRACT_DELETE_SUCCESS = 'CONTRACT_DELETE_SUCCESS';
export const CONTRACT_DELETE_FAIL = 'CONTRACT_DELETE_FAIL';