export const GET_ALL_PODACI_ZA_EMS_REQUEST = 'GET_ALL_PODACI_ZA_EMS_REQUEST';
export const GET_ALL_PODACI_ZA_EMS_SUCCESS = 'GET_ALL_PODACI_ZA_EMS_SUCCESS';
export const GET_ALL_PODACI_ZA_EMS_RESET = 'GET_ALL_PODACI_ZA_EMS_RESET';
export const GET_ALL_PODACI_ZA_EMS_FAIL = 'GET_ALL_PODACI_ZA_EMS_FAIL';

export const GET_SINGLE_EMS_REQUEST = 'GET_SINGLE_EMS_REQUEST';
export const GET_SINGLE_EMS_SUCCESS = 'GET_SINGLE_EMS_SUCCESS';
export const GET_SINGLE_EMS_FAIL = 'GET_SINGLE_EMS_FAIL';
export const GET_SINGLE_EMS_RESET = 'GET_SINGLE_EMS_RESET';

export const SAVE_PODACI_ZA_EMS_REQUEST = 'SAVE_PODACI_ZA_EMS_REQUEST';
export const SAVE_PODACI_ZA_EMS_SUCCESS = 'SAVE_PODACI_ZA_EMS_SUCCESS';
export const UPDATE_PODACI_ZA_EMS_SUCCESS = 'UPDATE_PODACI_ZA_EMS_SUCCESS';
export const SAVE_PODACI_ZA_EMS_FAIL = 'SAVE_PODACI_ZA_EMS_FAIL';