export const GET_KURS_EURA_REQUEST = 'GET_KURS_EURA_REQUEST';
export const GET_KURS_EURA_SUCCESS = 'GET_KURS_EURA_SUCCESS';
export const GET_KURS_EURA_RESET = 'GET_KURS_EURA_RESET';
export const GET_KURS_EURA_FAIL = 'GET_KURS_EURA_FAIL';

export const SAVE_EURO_REQUEST = 'SAVE_EURO_REQUEST';
export const SAVE_EURO_SUCCESS = 'SAVE_EURO_SUCCESS';
export const SAVE_EURO_FAIL = 'SAVE_EURO_FAIL';


export const GET_ALL_KURS_EURA_REQUEST = 'GET_ALL_KURS_EURA_REQUEST';
export const GET_ALL_KURS_EURA_SUCCESS = 'GET_ALL_KURS_EURA_SUCCESS';
export const GET_ALL_KURS_EURA_RESET = 'GET_ALL_KURS_EURA_RESET';
export const GET_ALL_KURS_EURA_FAIL = 'GET_ALL_KURS_EURA_FAIL';

