export const METERING_SAVE_REQUEST = 'METERING_SAVE_REQUEST';
export const METERING_SAVE_SUCCESS = 'METERING_SAVE_SUCCESS';
export const METERING_SAVE_FAIL = 'METERING_SAVE_FAIL';

export const GET_ALL_METERING_BY_METERID_REQUEST = 'GET_ALL_METERING_BY_METERID_REQUEST'
export const GET_ALL_METERING_BY_METERID_SUCCESS = 'GET_ALL_METERING_BY_METERID_SUCCESS'
export const GET_ALL_METERING_BY_METERID_FAIL = 'GET_ALL_METERING_BY_METERID_FAIL'
export const GET_ALL_METERING_BY_METERID_UPDATE = 'GET_ALL_METERING_BY_METERID_UPDATE'

export const METERING_DELETE_REQUEST = 'METERING_DELETE_REQUEST';
export const METERING_DELETE_SUCCESS = 'METERING_DELETE_SUCCESS';
export const METERING_DELETE_FAIL = 'METERING_DELETE_FAIL';

export const GET_METERING_BY_METER_IDS_REQUEST = 'GET_METERING_BY_METER_IDS_REQUEST'
export const GET_METERING_BY_METER_IDS_SUCCESS = 'GET_METERING_BY_METER_IDS_SUCCESS'
export const GET_METERING_BY_METER_IDS_FAIL = 'GET_METERING_BY_METER_IDS_FAIL'