export const GET_ALL_METERS_REQUEST = 'GET_ALL_METERS_REQUEST';
export const GET_ALL_METERS_SUCCESS = 'GET_ALL_METERS_SUCCESS';
export const GET_ALL_METERS_FAIL = 'GET_ALL_METERS_FAIL';
export const ALL_METERS_UPDATE = 'ALL_METERS_UPDATE';

export const GET_SINGLE_METER_REQUEST = 'GET_SINGLE_METER_REQUEST';
export const GET_SINGLE_METER_SUCCESS = 'GET_SINGLE_METER_SUCCESS';
export const GET_SINGLE_METER_FAIL = 'GET_SINGLE_METER_FAIL';

export const METER_SAVE_REQUEST = 'METER_SAVE_REQUEST';
export const METER_SAVE_SUCCESS = 'METER_SAVE_SUCCESS';
export const METER_SAVE_FAIL = 'METER_SAVE_FAIL';

export const METER_DELETE_REQUEST = 'METER_DELETE_REQUEST';
export const METER_DELETE_SUCCESS = 'METER_DELETE_SUCCESS';
export const METER_DELETE_FAIL = 'METER_DELETE_FAIL';