export const GET_ALL_MREZARINA_REQUEST = 'GET_ALL_MREZARINA_REQUEST';
export const GET_ALL_MREZARINA_SUCCESS = 'GET_ALL_MREZARINA_SUCCESS';
export const GET_ALL_MREZARINA_RESET = 'GET_ALL_MREZARINA_RESET';
export const GET_ALL_MREZARINA_FAIL = 'GET_ALL_MREZARINA_FAIL';

export const GET_MREZARINA_REQUEST = 'GET_MREZARINA_REQUEST';
export const GET_MREZARINA_SUCCESS = 'GET_MREZARINA_SUCCESS';
export const GET_MREZARINA_FAIL = 'GET_MREZARINA_FAIL';
export const GET_MREZARINA_RESET = 'GET_MREZARINA_RESET'

export const MREZARINA_UPDATE_REQUEST = 'MREZARINA_UPDATE_REQUEST';
export const MREZARINA_UPDATE_SUCCESS = 'MREZARINA_UPDATE_SUCCESS';
export const MREZARINA_UPDATE_FAIL = 'MREZARINA_UPDATE_FAIL';

export const NEW_MREZARINA_REQUEST = 'NEW_MREZARINA_REQUEST';
export const NEW_MREZARINA_SUCCESS = 'NEW_MREZARINA_SUCCESS';
export const NEW_MREZARINA_FAIL = 'NEW_MREZARINA_FAIL';