export const GET_ALL_NAMETI_REQUEST = 'GET_ALL_NAMETI_REQUEST';
export const GET_ALL_NAMETI_SUCCESS = 'GET_ALL_NAMETI_SUCCESS';
export const GET_ALL_NAMETI_RESET = 'GET_ALL_NAMETI_RESET';
export const GET_ALL_NAMETI_FAIL = 'GET_ALL_NAMETI_FAIL';

export const GET_NAMETI_REQUEST = 'GET_NAMETI_REQUEST';
export const GET_NAMETI_SUCCESS = 'GET_NAMETI_SUCCESS';
export const GET_NAMETI_RESET = 'GET_NAMETI_RESET';
export const GET_NAMETI_FAIL = 'GET_NAMETI_FAIL';

export const SAVE_NAMETI_REQUEST = 'SAVE_NAMETI_REQUEST';
export const SAVE_NAMETI_SUCCESS = 'SAVE_NAMETI_SUCCESS';
export const SAVE_NAMETI_FAIL = 'SAVE_NAMETI_FAIL';

export const NAMETI_UPDATE_REQUEST = 'NAMETI_UPDATE_REQUEST';
export const NAMETI_UPDATE_SUCCESS = 'NAMETI_UPDATE_SUCCESS';
export const NAMETI_UPDATE_FAIL = 'NAMETI_UPDATE_FAIL';